version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  go-server:
    image: golang:1.20-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go mod download && go build -o main . && ./main"
    expose:
      - "8080"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
